DECODING_CODES = {
    '00' : 'Ok',
    '01' : 'Client added',
    '02' : 'Client no found',
    '03' : 'No Clients',
    '04' : 'Client is alredy exist',
    '05' : 'Client updated',
    '06' : 'Stock added',
    '07' : 'Stock no found',
    '08' : 'No Stocks',
    '09' : 'Stock is alredy exist',
    '10' : 'Stock updated',
    '11' : 'Product added',
    '12' : 'Product not found',
    '13' : 'No Products',
    '14' : 'Product is alredy exist',
    '15' : 'Product updated',
    '16' : 'Coming added',
    '17' : 'Coming not found',
    '18' : 'No Comings',
    '19' : 'Coming is alredy exist',
    '20' : 'Coming updated',
    '21' : 'Coming added',
}
TEXT_IF_NO_CODE = 'No error message'
